Repository Project-calender/project-calendar, pull requests merged in 2022-08, with the labels that each got.

#172 feat: 이벤트 참석자 목록 구현 (#169)
  front/src/components/calendar/EventBar/index.jsx
  front/src/components/calendar/EventBar/style.module.css
  front/src/components/calendar/month/CalendarBody/Date/EventList/ReadMoreTitle/index.jsx
  front/src/components/calendar/month/CalendarBody/Date/EventList/index.jsx
  front/src/components/calendar/month/CalendarBody/Date/index.jsx
  front/src/constants/api.js
  front/src/hooks/useEventModal.js
  front/src/modal/component/EventDetailModal/EventAttendanceButtons/index.jsx
  front/src/modal/component/EventDetailModal/EventAttendanceButtons/style.module.css
  front/src/modal/component/EventDetailModal/EventMemberList/index.jsx
  front/src/modal/component/EventDetailModal/EventMemberList/style.module.css
  front/src/modal/component/EventDetailModal/index.jsx
  front/src/modal/component/EventDetailModal/style.module.css
  front/src/modal/component/EventListModal/EventContainer/index.jsx
  front/src/modal/layout/EventDetailMaodalLayout/index.jsx
  front/src/store/events.js
Labels: 🐛 fix, ✨ feat, 👨‍💻 FE

#178 fix: getAllEvents API 데이터 구조 변경
  front/src/components/calendar/EventBar/index.jsx
  front/src/components/calendar/EventBar/style.module.css
  front/src/components/calendar/month/CalendarBody/Date/EventList/index.jsx
  front/src/components/calendar/month/CalendarBody/Date/index.jsx
  front/src/hooks/useDragDate.js
  front/src/modal/component/EventDetailModal/EventAttendanceButtons/index.jsx
  front/src/modal/component/EventDetailModal/index.jsx
  front/src/store/events.js
  front/src/store/thunk/index.js
Labels: 🐛 fix, 👨‍💻 FE

#179 fix: 이벤트 목록 모달창 외부에서 마우스 스크롤 시 에러 해결
  front/src/components/calendar/EventBar/index.jsx
  front/src/components/calendar/month/CalendarBody/Date/EventList/index.jsx
  front/src/components/calendar/month/CalendarBody/Date/index.jsx
  front/src/components/common/CheckBox/index.jsx
  front/src/components/common/CheckBox/style.module.css
  front/src/modal/component/CreateEventModal/index.jsx
  front/src/modal/component/EventDetailModal/EventMemberList/index.jsx
  front/src/modal/component/EventDetailModal/EventMemberList/style.module.css
  front/src/modal/component/EventDetailModal/style.module.css
  front/src/modal/component/EventListModal/EventContainer/index.jsx
  front/src/modal/component/EventListModal/index.jsx
  front/src/store/selectors/calendars.js
  front/src/store/selectors/events.js
Labels: 🐛 fix, 👨‍💻 FE

#182 feat: 캘린더 표시/숨김 기능 구현 (#180, #181)
  front/src/components/Navbar/RightMenu/index.jsx
  front/src/components/SideBar/CalendarList/CalendarItem/index.jsx
  front/src/components/SideBar/CalendarList/index.jsx
  front/src/components/calendar/EventBar/index.jsx
  front/src/components/calendar/EventBar/style.module.css
  front/src/components/calendar/month/CalendarBody/Date/EventList/index.jsx
  front/src/components/calendar/year/MonthCalendar/CalendarBody/Date/index.jsx
  front/src/constants/api.js
  front/src/modal/component/EventDetailModal/index.jsx
  front/src/modal/component/EventListModal/EventContainer/index.jsx
  front/src/modal/component/EventListModal/index.jsx
  front/src/modal/component/EventListModal/style.module.css
  front/src/pages/Login/index.jsx
  front/src/store/calendars.js
  front/src/store/events.js
  front/src/store/selectors/user.js
  front/src/store/user.js
Labels: 🐛 fix, ✨ feat, 👨‍💻 FE

#186 feat: 이벤트 참석 및 종일 여부에 따른 이벤트바 UI 구현 (#183, #184)
  front/public/logo192.png
  front/src/components/calendar/EventBar/index.jsx
  front/src/components/calendar/EventBar/style.module.css
  front/src/components/calendar/EventTimeBar/index.jsx
  front/src/components/calendar/EventTimeBar/style.module.css
  front/src/components/calendar/month/CalendarBody/Date/NewEvent/style.module.css
  front/src/components/calendar/year/MonthCalendar/CalendarBody/Date/index.jsx
  front/src/modal/component/EventDetailModal/index.jsx
  front/src/modal/component/EventListModal/EventContainer/index.jsx
  front/src/modal/component/EventListModal/style.module.css
  front/src/store/events.js
  front/src/store/thunk/index.js
  front/src/utils/moment.js
Labels: ✨ feat, 👨‍💻 FE

#190 feat: 캘린더 생성 기능 구현 (#187)
  front/src/components/SideBar/CalendarList/CalendarItem/index.jsx
  front/src/components/SideBar/CalendarList/CalendarItem/style.module.css
  front/src/components/SideBar/MyCalendarList/index.jsx
  front/src/components/SideBar/MyCalendarList/style.module.css
  front/src/components/SideBar/NewCalendarButton/index.jsx
  front/src/components/SideBar/NewCalendarButton/style.module.css
  front/src/components/SideBar/OtherCalendarList/index.jsx
  front/src/components/SideBar/OtherCalendarList/style.module.css
  front/src/components/calendar/EventColorOption/index.jsx
  front/src/components/calendar/EventColorOption/style.module.css
  front/src/components/calendar/year/MonthCalendar/CalendarBody/Date/index.jsx
  front/src/components/common/Input/index.jsx
  front/src/components/common/Input/style.module.css
  front/src/components/common/TextField/index.jsx
  front/src/components/common/TextField/style.module.css
  front/src/components/common/Tooltip/index.jsx
  front/src/components/common/Tooltip/style.module.css
  front/src/constants/api.js
  front/src/context/EventModalContext.js
  front/src/hooks/useEventModal.js
  front/src/modal/component/CreateCalendarModal/index.jsx
  front/src/modal/component/CreateCalendarModal/style.module.css
  front/src/modal/component/CreateEventModal/index.jsx
  front/src/modal/component/CreateEventModal/style.module.css
  front/src/modal/component/EventColorListModal/index.jsx
  front/src/modal/component/EventColorModal/index.jsx
  front/src/modal/component/EventColorModal/style.module.css
  front/src/modal/component/EventDetailModal/index.jsx
  front/src/modal/component/EventListModal/index.jsx
  front/src/modal/component/ListModal/index.jsx
  front/src/modal/layout/CreateCalendarModalLayout/index.jsx
  front/src/modal/layout/CreateEventModalLayout/index.jsx
  front/src/modal/layout/CreateModalLayout/index.jsx
  front/src/modal/layout/EventDetailMaodalLayout/index.jsx
  front/src/modal/layout/EventListModalLayout/index.jsx
  front/src/pages/MonthCalendarPage/index.jsx
  front/src/store/calendars.js
  front/src/store/events.js
  front/src/store/selectors/user.js
  front/src/store/thunk/calendar.js
  front/src/store/thunk/event.js
Labels: ✨ feat, 👨‍💻 FE

#192 feat: 캘린더 수정, 삭제 기능 구현(#191)
  back/models/calendar.js
  back/routes/calendar.js
  back/swagger.yaml
  back/swagger/calendarAPI.yaml
Labels: ✨ feat, 👨‍💻 BE

#193 Calendar edit
  back/routes/calendar.js
  back/swagger.yaml
  back/swagger/calendarAPI.yaml
Labels: 🛠 refactor, 👨‍💻 BE

#195 Private calendar edit api
  back/app.js
  back/routes/privateCalendar.js
  back/swagger.yaml
  back/swagger/calendarAPI.yaml
  back/swagger/privateCalendarAPI.yaml
Labels: ✨ feat, 👨‍💻 BE

#199 Fix
  back/swagger.yaml
  back/swagger/alertAPI.yaml
  back/swagger/calendarAPI.yaml
  back/swagger/privateCalendarAPI.yaml
Labels: 🐛 fix, 👨‍💻 BE

#200 refactor: 전달 파라미터 변경
  back/routes/privateCalendar.js
  back/swagger/privateCalendarAPI.yaml
Labels: 🛠 refactor, 👨‍💻 BE

#201 refator: 응답 객체명 변경
  back/routes/privateCalendar.js
Labels: 🛠 refactor, 👨‍💻 BE

#202 Fix
  back/routes/privateCalendar.js
Labels: 🐛 fix, 👨‍💻 BE

#204 feat: 캘린더 수정 및 삭제 기능 구현 (#188, #198)
  front/src/components/Navbar/style.module.css
  front/src/components/SideBar/CalendarList/CalendarItem/index.jsx
  front/src/components/SideBar/CalendarList/CalendarItem/style.module.css
  front/src/components/SideBar/CalendarList/OptionButtons/index.jsx
  front/src/components/SideBar/CalendarList/OptionButtons/style.module.css
  front/src/components/SideBar/index.jsx
  front/src/components/SideBar/style.module.css
  front/src/components/calendar/EventColor/index.jsx
  front/src/components/calendar/EventColor/style.module.css
  front/src/components/common/CheckBox/index.jsx
  front/src/components/common/Modal/index.jsx
  front/src/components/common/Modal/style.module.css
  front/src/components/common/Tooltip/style.module.css
  front/src/constants/api.js
  front/src/context/EventModalContext.js
  front/src/hooks/useEventModal.js
  front/src/modal/component/CalendarOptionModal/index.jsx
  front/src/modal/component/CalendarOptionModal/style.module.css
  front/src/modal/component/CreateEventModal/index.jsx
  front/src/modal/component/DeleteCalendarModal/index.jsx
  front/src/modal/component/DeleteCalendarModal/style.module.css
  front/src/modal/component/EventColorModal/index.jsx
  front/src/modal/layout/EventListModalLayout/index.jsx
  front/src/modal/layout/ModalLayout/index.jsx
  front/src/store/calendars.js
  front/src/store/events.js
  front/src/store/selectors/user.js
  front/src/store/thunk/calendar.js
  front/src/store/thunk/event.js
  front/src/store/thunk/user.js
  front/src/store/user.js
Labels: ✨ feat, 👨‍💻 FE

#205 Fixfix
  back/routes/calendar.js
  back/routes/privateCalendar.js
Labels: 🐛 fix, 👨‍💻 BE

#206 fix: fix error
  back/routes/privateCalendar.js
Labels: 🐛 fix, 👨‍💻 BE

#210 fix: 캘린더 삭제 및 수정 요청 에러 해결
  front/src/components/SideBar/AddEventButton/index.jsx
  front/src/components/SideBar/AddEventButton/style.module.css
  front/src/components/SideBar/CalendarList/CalendarItem/index.jsx
  front/src/components/calendar/EventBar/index.jsx
  front/src/components/calendar/EventColor/style.module.css
  front/src/components/calendar/EventTimeBar/index.jsx
  front/src/components/calendar/month/CalendarBody/Date/NewEvent/index.jsx
  front/src/components/calendar/month/CalendarBody/Date/NewEvent/style.module.css
  front/src/components/common/Modal/index.jsx
  front/src/components/common/TextField/style.module.css
  front/src/context/EventModalContext.js
  front/src/hooks/useCreateEventBar.js
  front/src/modal/component/AddEventButtonModal/index.jsx
  front/src/modal/component/AddEventButtonModal/style.module.css
  front/src/modal/component/CalendarOptionModal/index.jsx
  front/src/modal/component/CalendarOptionModal/style.module.css
  front/src/modal/component/CreateEventModal/index.jsx
  front/src/modal/component/EventColorModal/style.module.css
  front/src/modal/component/ListModal/index.jsx
  front/src/modal/component/ListModal/style.module.css
  front/src/modal/layout/CreateEventModalLayout/index.jsx
  front/src/pages/MonthCalendarPage/index.jsx
  front/src/store/events.js
  front/src/store/selectors/events.js
  front/src/store/thunk/calendar.js
  front/src/store/thunk/event.js
Labels: 🐛 fix, 👨‍💻 FE

#215 검색 기능 추가
  front/src/App.js
  front/src/components/Navbar/RightMenu/index.jsx
  front/src/components/Navbar/Search/index.jsx
  front/src/components/Navbar/Search/style.module.css
  front/src/components/Navbar/index.jsx
  front/src/components/SideBar/style.module.css
  front/src/components/searchDetall/index.jsx
  front/src/components/searchDetall/style.module.css
  front/src/constants/api.js
  front/src/constants/path.js
  front/src/modal/component/EventDetailModal/index.jsx
  front/src/pages/Join/index.jsx
  front/src/pages/Login/index.jsx
  front/src/store/index.js
  front/src/store/search.js
Labels: 👨‍💻 FE

#226 feat: 심플 이벤트 옵션 모달 구현 (#222)
  front/src/components/Navbar/RightMenu/index.jsx
  front/src/components/calendar/EventBar/index.jsx
  front/src/components/calendar/EventColor/index.jsx
  front/src/components/calendar/EventColor/style.module.css
  front/src/components/calendar/EventColorOption/index.jsx
  front/src/components/calendar/EventFillBar/index.jsx
  front/src/components/calendar/EventTimeBar/index.jsx
  front/src/components/calendar/MonthCalendar/CalendarBody/Date/EventList/ReadMoreTitle/index.jsx
  front/src/components/calendar/MonthCalendar/CalendarBody/Date/EventList/index.jsx
  front/src/components/calendar/MonthCalendar/index.jsx
  front/src/constants/api.js
  front/src/context/EventModalContext.js
  front/src/hooks/useDragDate.js
  front/src/modal/component/CalendarOptionModal/index.jsx
  front/src/modal/component/CreateEventModal/index.jsx
  front/src/modal/component/EventColorModal/index.jsx
  front/src/modal/component/SimpleEventOptionModal/index.js
  front/src/modal/component/SimpleEventOptionModal/style.module.css
  front/src/modal/layout/CreateCalendarModalLayout/index.jsx
  front/src/modal/layout/CreateEventModalLayout/index.jsx
  front/src/modal/layout/ModalLayout/index.jsx
  front/src/pages/AlertPage/index.jsx
  front/src/pages/Login/index.jsx
  front/src/pages/Main/index.jsx
  front/src/store/calendars.js
  front/src/store/events.js
  front/src/store/newEvent.js
  front/src/store/selectors/calendars.js
  front/src/store/selectors/user.js
  front/src/store/thunk/event.js
  front/src/store/user.js
Labels: ✨ feat, 👨‍💻 FE

#233 feat: 이벤트 초대 기능 구현 (#223)
  front/src/components/SideBar/CalendarList/OptionButtons/index.jsx
  front/src/components/SideBar/MiniCalendar/CalendarBody/Week/index.jsx
  front/src/components/SideBar/MiniCalendar/CalendarBody/index.jsx
  front/src/components/SideBar/MiniCalendar/CalendarHeader/index.jsx
  front/src/components/SideBar/MiniCalendar/index.jsx
  front/src/components/SideBar/index.jsx
  front/src/components/SideBar/style.module.css
  front/src/components/calendar/EventBar/EventFillBar/index.jsx
  front/src/components/calendar/EventBar/EventFillBar/style.module.css
  front/src/components/calendar/EventBar/EventTimeBar/index.jsx
  front/src/components/calendar/EventBar/EventTimeBar/style.module.css
  front/src/components/calendar/EventBar/index.jsx
  front/src/components/calendar/MonthCalendar/CalendarBody/Date/EventList/index.jsx
  front/src/components/calendar/MonthCalendar/CalendarBody/Date/NewEvent/index.jsx
  front/src/components/calendar/MonthCalendar/CalendarBody/Date/index.jsx
  front/src/components/calendar/MonthCalendar/index.jsx
  front/src/components/common/Input/index.jsx
  front/src/constants/api.js
  front/src/context/EventModalContext.js
  front/src/index.css
  front/src/modal/component/AddEventButtonModal/index.jsx
  front/src/modal/component/AlertListModal/index.jsx
  front/src/modal/component/AlertListModal/style.module.css
  front/src/modal/component/CreateEventModal/DateTitle/index.jsx
  front/src/modal/component/CreateEventModal/DateTitle/style.module.css
  front/src/modal/component/CreateEventModal/InviteInput/index.jsx
  front/src/modal/component/CreateEventModal/InviteInput/style.module.css
  front/src/modal/component/CreateEventModal/InviteMembers/index.jsx
  front/src/modal/component/CreateEventModal/InviteMembers/style.module.css
  front/src/modal/component/CreateEventModal/index.jsx
  front/src/modal/component/CreateEventModal/style.module.css
  front/src/modal/component/EventDetailModal/index.jsx
  front/src/modal/component/ListModal/style.module.css
  front/src/modal/component/MiniCalendarModal/index.jsx
  front/src/modal/component/MiniCalendarModal/style.module.css
  front/src/modal/component/ResignCalendarModal/index.jsx
  front/src/modal/component/ResignCalendarModal/style.module.css
  front/src/modal/component/SimpleEventOptionModal/index.jsx
  front/src/modal/component/TimeListModal/index.jsx
  front/src/modal/component/TimeListModal/style.module.css
  front/src/pages/AlertPage/index.jsx
  front/src/pages/MonthCalendarPage/index.jsx
  front/src/store/calendars.js
  front/src/store/events.js
  front/src/store/newEvent.js
  front/src/store/selectors/calendars.js
  front/src/store/selectors/newEvent.js
  front/src/store/thunk/calendar.js
  front/src/store/thunk/event.js
  front/src/utils/moment.js
Labels: ✨ feat, 👨‍💻 FE

#239 feat: 이벤트 생성의 이벤트 알림 기능 구현 (#234)
  front/src/components/SideBar/CalendarList/OptionButtons/index.jsx
  front/src/components/alert/CustomAlertOfAllDay/index.jsx
  front/src/components/alert/CustomAlertOfAllDay/style.module.css
  front/src/components/alert/CustomAlertOfNotAllDay/index.jsx
  front/src/components/alert/CustomAlertOfNotAllDay/style.module.css
  front/src/components/calendar/EventBar/index.jsx
  front/src/components/calendar/MonthCalendar/index.jsx
  front/src/components/common/Input/index.jsx
  front/src/components/common/Line/index.jsx
  front/src/components/common/Line/style.module.css
  front/src/components/common/Modal/style.module.css
  front/src/constants/api.js
  front/src/context/EventModalContext.js
  front/src/modal/component/CreateEventModal/AlertContainer/AlertList/index.jsx
  front/src/modal/component/CreateEventModal/AlertContainer/AlertList/style.module.css
  front/src/modal/component/CreateEventModal/AlertContainer/index.jsx
  front/src/modal/component/CreateEventModal/AlertContainer/style.module.css
  front/src/modal/component/CreateEventModal/BusyContainer/index.jsx
  front/src/modal/component/CreateEventModal/BusyContainer/style.module.css
  front/src/modal/component/CreateEventModal/CalendarContainer/index.jsx
  front/src/modal/component/CreateEventModal/CalendarContainer/style.module.css
  front/src/modal/component/CreateEventModal/CalendarPreviewContainer/index.jsx
  front/src/modal/component/CreateEventModal/CalendarPreviewContainer/style.module.css
  front/src/modal/component/CreateEventModal/DateTitle/index.jsx
  front/src/modal/component/CreateEventModal/InviteInput/style.module.css
  front/src/modal/component/CreateEventModal/InviteMemberList/index.jsx
  front/src/modal/component/CreateEventModal/InviteMemberList/style.module.css
  front/src/modal/component/CreateEventModal/MemoContainer/index.jsx
  front/src/modal/component/CreateEventModal/MemoContainer/style.module.css
  front/src/modal/component/CreateEventModal/MemoPreviewContainer/index.jsx
  front/src/modal/component/CreateEventModal/MemoPreviewContainer/style.module.css
  front/src/modal/component/CreateEventModal/PermissionContainer/index.jsx
  front/src/modal/component/CreateEventModal/PermissionContainer/style.module.css
  front/src/modal/component/CreateEventModal/index.jsx
  front/src/modal/component/CreateEventModal/style.module.css
  front/src/modal/component/CustomAlertModal/index.jsx
  front/src/modal/component/CustomAlertModal/style.module.css
  front/src/modal/component/EventDetailModal/index.jsx
  front/src/modal/component/ListModal/index.jsx
  front/src/modal/component/MiniCalendarModal/index.jsx
  front/src/modal/component/ResignCalendarModal/index.jsx
  front/src/modal/component/TimeListModal/index.jsx
  front/src/modal/layout/CreateEventModalLayout/index.jsx
  front/src/store/calendars.js
  front/src/store/events.js
  front/src/store/newEvent.js
  front/src/store/selectors/newEvent.js
  front/src/store/thunk/event.js
  front/src/utils/moment.js
Labels: ✨ feat, 🛠 refactor, 👨‍💻 FE

#244 [feat]설정 페이지 구현
  front/package-lock.json
  front/package.json
  front/src/App.js
  front/src/components/Navbar/RightMenu/index.jsx
  front/src/components/Navbar/Search/index.jsx
  front/src/components/Navbar/Setting/index.jsx
  front/src/components/Navbar/Setting/style.module.css
  front/src/components/Navbar/index.jsx
  front/src/constants/api.js
  front/src/constants/path.js
  front/src/pages/Join/index.jsx
  front/src/pages/Main/index.jsx
  front/src/pages/Setting/Content/AnotherCalendar/Subscribe/index.jsx
  front/src/pages/Setting/Content/AnotherCalendar/Subscribe/style.module.css
  front/src/pages/Setting/Content/AnotherCalendar/index.jsx
  front/src/pages/Setting/Content/AnotherCalendar/style.module.css
  front/src/pages/Setting/Content/Invite/index.jsx
  front/src/pages/Setting/Content/Invite/style.module.css
  front/src/pages/Setting/Content/MyCalendar/Authority/index.jsx
  front/src/pages/Setting/Content/MyCalendar/Authority/style.module.css
  front/src/pages/Setting/Content/MyCalendar/CalendarDelete/PopUp/index.jsx
  front/src/pages/Setting/Content/MyCalendar/CalendarDelete/PopUp/style.module.css
  front/src/pages/Setting/Content/MyCalendar/CalendarDelete/index.jsx
  front/src/pages/Setting/Content/MyCalendar/CalendarDelete/style.module.css
  front/src/pages/Setting/Content/MyCalendar/ChangeName/index.jsx
  front/src/pages/Setting/Content/MyCalendar/ChangeName/style.module.css
  front/src/pages/Setting/Content/MyCalendar/index.jsx
  front/src/pages/Setting/Content/MyCalendar/style.module.css
  front/src/pages/Setting/Content/index.jsx
  front/src/pages/Setting/Content/style.module.css
  front/src/pages/Setting/Sidebar/index.jsx
  front/src/pages/Setting/Sidebar/style.module.css
  front/src/pages/Setting/index.jsx
  front/src/pages/Setting/style.module.css
Labels: 👨‍💻 FE

#247 feat: 이벤트 생성의 서브 모달 추가 기능 구현 (#242)
  front/src/components/alert/CustomAlertOfAllDay/index.jsx
  front/src/components/alert/CustomAlertOfNotAllDay/index.jsx
  front/src/components/calendar/EventBar/index.jsx
  front/src/constants/api.js
  front/src/context/EventModalContext.js
  front/src/modal/component/CreateEventModal/AlertContainer/AlertList/index.jsx
  front/src/modal/component/CreateEventModal/BusyContainer/index.jsx
  front/src/modal/component/CreateEventModal/CalendarContainer/index.jsx
  front/src/modal/component/CreateEventModal/DateTitleContainer/index.jsx
  front/src/modal/component/CreateEventModal/DateTitleContainer/style.module.css
  front/src/modal/component/CreateEventModal/PermissionContainer/index.jsx
  front/src/modal/component/CreateEventModal/index.jsx
  front/src/modal/component/CreateEventModal/style.module.css
  front/src/modal/component/ListModal/index.jsx
  front/src/modal/component/ListModal/style.module.css
  front/src/modal/component/MiniCalendarModal/index.jsx
  front/src/modal/component/TimeListModal/index.jsx
  front/src/modal/layout/CreateEventModalLayout/index.jsx
  front/src/store/events.js
  front/src/store/newEvent.js
  front/src/store/thunk/event.js
Labels: 🐛 fix, ✨ feat, 👨‍💻 FE

#258 feat: 이벤트 생성 입력 데이터 제한 설정 및 마우스 드래그로 이동 기능 구현 (#249, #257)
  front/src/components/alert/CustomAlertOfAllDay/index.jsx
  front/src/components/alert/CustomAlertOfAllDay/style.module.css
  front/src/components/alert/CustomAlertOfNotAllDay/index.jsx
  front/src/components/alert/CustomAlertOfNotAllDay/style.module.css
  front/src/components/calendar/EventBar/index.jsx
  front/src/components/common/Input/index.jsx
  front/src/components/common/Line/style.module.css
  front/src/components/common/Modal/index.jsx
  front/src/components/common/Modal/style.module.css
  front/src/components/common/TextField/index.jsx
  front/src/components/common/Tooltip/index.jsx
  front/src/hooks/useDraggable.js
  front/src/modal/component/CreateEventModal/DateTitleContainer/style.module.css
  front/src/modal/component/CreateEventModal/InviteMemberList/index.jsx
  front/src/modal/component/CreateEventModal/InviteMemberList/style.module.css
  front/src/modal/component/CreateEventModal/index.jsx
  front/src/modal/component/CreateEventModal/style.module.css
  front/src/modal/component/CustomAlertModal/index.jsx
  front/src/pages/Main/index.jsx
  front/src/store/newEvent.js
  front/src/utils/delay.js
Labels: ✨ feat, 👨‍💻 FE

#262 fix: 이벤트 상세보기 API의 응답 데이터 수정 (#261)
  front/src/components/calendar/EventBar/index.jsx
  front/src/components/calendar/EventBar/style.module.css
  front/src/components/searchDetall/index.jsx
  front/src/modal/component/EventDetailModal/EventMemberList/style.module.css
  front/src/modal/component/EventDetailModal/index.jsx
  front/src/store/thunk/event.js
Labels: 🐛 fix, 👨‍💻 FE
