Repository Project-calender/project-calendar, pull requests merged in 2022-07, with the labels that each got.

#43 refactor: SideBar 컴포넌트 및 date 상태 데이터 (#42)
  front/README.md
  front/src/components/Navbar/LeftMenu/index.jsx
  front/src/components/SideBar/MiniCalendar/Week/index.jsx
  front/src/components/SideBar/MiniCalendar/Week/style.module.css
  front/src/components/calendar/calendar.module.css
  front/src/components/calendar/index.jsx
  front/src/store/date.js
  front/src/store/selectors/date.js
  front/src/utils/moment.js
Labels: 🛠 refactor, 👨‍💻 FE

#45 Login,join 페이지 구현
  front/public/img/login/google_logo.png
  front/public/img/login/login_img.png
  front/public/index.html
  front/src/App.css
  front/src/App.js
  front/src/components/Navbar/LeftMenu/style.module.css
  front/src/components/Navbar/RightMenu/index.jsx
  front/src/components/Navbar/RightMenu/style.module.css
  front/src/components/Navbar/style.module.css
  front/src/pages/Join/index.jsx
  front/src/pages/Join/style.module.css
  front/src/pages/Login/index.jsx
  front/src/pages/Login/style.module.css
  front/src/store/date.js
Labels: 👨‍💻 FE

#51 [feat] 유저, 캘린더, 이벤트 라우터 완성 커밋 병합
  back/app.js
  back/models/calendar.js
  back/models/calendarMember.js
  back/models/event.js
  back/models/eventMember.js
  back/models/index.js
  back/models/invite.js
  back/models/privateEvent.js
  back/routes/calendar.js
  back/routes/event.js
  back/routes/middlewares.js
  back/routes/user.js
Labels: ✨ feat, 👨‍💻 BE

#52 merge
  back/routes/calendar.js
  back/routes/event.js
Labels: ✨ feat, 👨‍💻 BE

#53 feat: 메인 캘린더 - Year, Month 단위 캘린더 (#47, #48)
  front/src/App.js
  front/src/components/SideBar/CalendarList/CalendarInfo/style.module.css
  front/src/components/SideBar/MiniCalendar/CalendarBody/Week/index.jsx
  front/src/components/SideBar/MiniCalendar/CalendarBody/Week/style.module.css
  front/src/components/SideBar/MiniCalendar/CalendarBody/WeekDaysHeader/index.jsx
  front/src/components/SideBar/MiniCalendar/CalendarBody/WeekDaysHeader/style.module.css
  front/src/components/SideBar/MiniCalendar/CalendarBody/index.jsx
  front/src/components/SideBar/MiniCalendar/CalendarBody/style.module.css
  front/src/components/SideBar/MiniCalendar/index.jsx
  front/src/components/SideBar/MiniCalendar/style.module.css
  front/src/components/SideBar/style.module.css
  front/src/components/calendar/month/CalendarBody/Date/index.jsx
  front/src/components/calendar/month/CalendarBody/index.jsx
  front/src/components/calendar/month/CalendarBody/style.module.css
  front/src/components/calendar/month/WeekDayHeader/index.jsx
  front/src/components/calendar/year/MonthCalendar/CalendarBody/Week/index.jsx
  front/src/components/calendar/year/MonthCalendar/CalendarBody/Week/style.module.css
  front/src/components/calendar/year/MonthCalendar/CalendarBody/WeekDaysHeader/index.jsx
  front/src/components/calendar/year/MonthCalendar/CalendarBody/WeekDaysHeader/style.module.css
  front/src/components/calendar/year/MonthCalendar/CalendarBody/index.jsx
  front/src/components/calendar/year/MonthCalendar/CalendarBody/style.module.css
  front/src/components/calendar/year/MonthCalendar/index.jsx
  front/src/components/calendar/year/MonthCalendar/style.module.css
  front/src/components/common/Tooltip/style.module.css
  front/src/index.css
  front/src/pages/MonthCalendarPage/index.jsx
  front/src/pages/MonthCalendarPage/style.module.css
  front/src/pages/YearCalendarPage/index.jsx
  front/src/pages/YearCalendarPage/style.module.css
  front/src/utils/moment.js
Labels: ✨ feat, 👨‍💻 FE

#57 feat: Main 캘린더의 Month 캘린더 컴포넌트 UI 구현 (#48)
  front/public/img/side_bar_plus.png
  front/src/App.js
  front/src/components/Navbar/LeftMenu/index.jsx
  front/src/components/Navbar/RightMenu/index.jsx
  front/src/components/Navbar/index.jsx
  front/src/components/SideBar/AddEventButton/index.jsx
  front/src/components/SideBar/AddEventButton/style.module.css
  front/src/components/SideBar/CalendarList/index.jsx
  front/src/components/SideBar/CalendarList/style.module.css
  front/src/components/SideBar/MiniCalendar/CalendarBody/Week/index.jsx
  front/src/components/SideBar/MiniCalendar/CalendarBody/Week/style.module.css
  front/src/components/SideBar/SubscriptionCalendarList/style.module.css
  front/src/components/SideBar/index.jsx
  front/src/components/SideBar/style.module.css
  front/src/components/calendar/month/CalendarBody/Date/index.jsx
  front/src/components/calendar/month/CalendarBody/Date/style.module.css
  front/src/components/calendar/month/CalendarBody/Week/index.jsx
  front/src/components/calendar/month/CalendarBody/index.jsx
  front/src/components/calendar/month/CalendarBody/style.module.css
  front/src/components/calendar/month/WeekDayHeader/index.jsx
  front/src/components/calendar/month/WeekDayHeader/style.module.css
  front/src/components/calendar/year/MonthCalendar/CalendarBody/Week/index.jsx
  front/src/components/calendar/year/MonthCalendar/CalendarBody/Week/style.module.css
  front/src/constants/path.js
  front/src/pages/Main/index.jsx
  front/src/pages/MonthCalendarPage/index.jsx
  front/src/pages/MonthCalendarPage/style.module.css
  front/src/pages/YearCalendarPage/style.module.css
  front/src/store/date.js
  front/src/utils/moment.js
Labels: 🐛 fix, ✨ feat, 👨‍💻 FE

#60 Main 캘린더의 day 컴포넌트 UI 구현
  front/src/App.js
  front/src/components/calendar/day/CalendarBody/index.jsx
  front/src/components/calendar/day/CalendarBody/style.module.css
  front/src/components/calendar/day/DayHeader/index.jsx
  front/src/components/calendar/day/DayHeader/style.module.css
  front/src/pages/DayCalendarPage/index.jsx
  front/src/pages/DayCalendarPage/style.module.css
  front/src/pages/Join/index.jsx
  front/src/pages/Login/index.jsx
Labels: ✨ feat, 👨‍💻 FE

#63 [feat] Redis를 사용한 token 통신 기능 추가 #62
  back/app.js
  back/package-lock.json
  back/package.json
  back/passport/index.js
  back/passport/local.js
  back/routes/auth.js
  back/routes/middlewares.js
  back/routes/user.js
  back/utils/authJWT.js
  back/utils/jwt-util.js
  back/utils/redis.js
  back/utils/refresh.js
Labels: ✨ feat, 👨‍💻 BE

#64 merge
  back/app.js
  back/package.json
Labels: ✨ feat, 👨‍💻 BE

#65 feat: Month 캘린더에서 마우스 드래그 이벤트로 새로운 이벤트 생성 (#61)
  front/package.json
  front/src/components/SideBar/style.module.css
  front/src/components/calendar/month/CalendarBody/Date/index.jsx
  front/src/components/calendar/month/CalendarBody/Date/style.module.css
  front/src/components/calendar/month/CalendarBody/EventBar/index.jsx
  front/src/components/calendar/month/CalendarBody/EventBar/style.module.css
  front/src/components/calendar/year/MonthCalendar/CalendarBody/Week/index.jsx
  front/src/context/EventBarContext.js
  front/src/hooks/useDragDate.js
  front/src/hooks/useMonthEventBar.js
  front/src/hooks/useNavigateDayCalendar.js
  front/src/pages/MonthCalendarPage/index.jsx
  front/src/pages/MonthCalendarPage/style.module.css
  front/src/pages/YearCalendarPage/style.module.css
  front/src/utils/delay.js
Labels: ✨ feat, 👨‍💻 FE

#67 Login,join 수정
  front/package.json
  front/public/img/join/profile.png
  front/src/components/Navbar/RightMenu/index.jsx
  front/src/components/Navbar/RightMenu/style.module.css
  front/src/components/calendar/day/CalendarBody/index.jsx
  front/src/components/calendar/day/CalendarBody/style.module.css
  front/src/pages/Join/index.jsx
  front/src/pages/Join/style.module.css
  front/src/pages/Login/index.jsx
  front/src/pages/Login/style.module.css
  front/src/utils/token.js
Labels: 👨‍💻 FE

#73 fix:Login 실패시 상태코드 수정(400 > 401)
  back/routes/user.js
  front/src/components/Navbar/RightMenu/index.jsx
  front/src/pages/Login/index.jsx
Labels: 🐛 fix, 👨‍💻 BE

#83 토큰 에러 해결
  back/routes/user.js
  back/utils/authJWT.js
  back/utils/jwt-util.js
  back/utils/refresh.js
Labels: 🐛 fix, 👨‍💻 BE

#87 feat: 월 단위 캘린더 이벤트 표시, 캘린더 및 이벤트 상태 데이터 구현 (#61, #66, #86)
  front/package.json
  front/public/img/check-solid.svg
  front/src/App.js
  front/src/components/Navbar/LeftMenu/index.jsx
  front/src/components/Navbar/RightMenu/index.jsx
  front/src/components/SideBar/AddEventButton/index.jsx
  front/src/components/SideBar/CalendarList/CalendarInfo/index.jsx
  front/src/components/SideBar/CalendarList/CalendarInfo/style.module.css
  front/src/components/SideBar/CalendarList/CalendarItem/index.jsx
  front/src/components/SideBar/CalendarList/CalendarItem/style.module.css
  front/src/components/SideBar/CalendarList/CalendarSummary/index.jsx
  front/src/components/SideBar/CalendarList/OptionButtons/index.jsx
  front/src/components/SideBar/CalendarList/OptionButtons/style.module.css
  front/src/components/SideBar/CalendarList/index.jsx
  front/src/components/SideBar/CalendarList/style.module.css
  front/src/components/SideBar/MiniCalendar/CalendarBody/Week/index.jsx
  front/src/components/SideBar/MiniCalendar/index.jsx
  front/src/components/SideBar/MyCalendarList/index.jsx
  front/src/components/SideBar/OtherCalendarList/index.jsx
  front/src/components/SideBar/OtherCalendarList/style.module.css
  front/src/components/SideBar/index.jsx
  front/src/components/SideBar/style.module.css
  front/src/components/calendar/month/CalendarBody/Date/EventBar/index.jsx
  front/src/components/calendar/month/CalendarBody/Date/EventBar/style.module.css
  front/src/components/calendar/month/CalendarBody/Date/EventList/ReadMoreTitle/index.jsx
  front/src/components/calendar/month/CalendarBody/Date/EventList/ReadMoreTitle/style.module.css
  front/src/components/calendar/month/CalendarBody/Date/EventList/index.jsx
  front/src/components/calendar/month/CalendarBody/Date/EventList/style.module.css
  front/src/components/calendar/month/CalendarBody/Date/NewEvent/index.jsx
  front/src/components/calendar/month/CalendarBody/Date/NewEvent/style.module.css
  front/src/components/calendar/month/CalendarBody/Date/index.jsx
  front/src/components/calendar/month/CalendarBody/Date/style.module.css
  front/src/components/calendar/month/CalendarBody/EventBar/index.jsx
  front/src/components/calendar/month/CalendarBody/EventBar/style.module.css
  front/src/components/calendar/year/MonthCalendar/CalendarBody/Week/index.jsx
  front/src/constants/api.js
  front/src/constants/path.js
  front/src/hooks/useNavigateDayCalendar.js
  front/src/index.js
  front/src/mocks/api.js
  front/src/mocks/calenders.json
  front/src/mocks/state.js
  front/src/pages/Join/index.jsx
  front/src/pages/Login/index.jsx
  front/src/pages/Main/index.jsx
  front/src/pages/MonthCalendarPage/index.jsx
  front/src/pages/YearCalendarPage/index.jsx
  front/src/store/calendars.js
  front/src/store/events.js
  front/src/store/index.js
  front/src/store/selectors/calendars.js
  front/src/store/selectors/date.js
  front/src/store/selectors/events.js
  front/src/store/selectors/user.js
  front/src/store/thunk/index.js
  front/src/store/user.js
  front/src/utils/moment.js
  front/src/utils/token.js
Labels: 🐛 fix, ✨ feat, 👨‍💻 FE

#89 test
  back/utils/authJWT.js
Labels: 👨‍💻 BE

#90 refresh try catch 적용
  back/routes/calendar.js
  back/utils/refresh.js
Labels: 👨‍💻 BE

#94 temp
  back/routes/calendar.js
  back/utils/authJWT.js
  back/utils/jwt-util.js
  back/utils/refresh.js
Labels: 👨‍💻 BE

#96 오류 수정
  back/routes/calendar.js
  back/utils/authJWT.js
  back/utils/redis.js
Labels: 🐛 fix, 👨‍💻 BE

#110 feat: Month 캘린더에 이벤트 표시 (#102)
  front/src/components/calendar/month/CalendarBody/Date/EventBar/index.jsx
  front/src/components/calendar/month/CalendarBody/Date/EventBar/style.module.css
  front/src/components/calendar/month/CalendarBody/Date/EventList/ReadMoreTitle/style.module.css
  front/src/components/calendar/month/CalendarBody/Date/EventList/index.jsx
  front/src/components/calendar/month/CalendarBody/Date/EventList/style.module.css
  front/src/hooks/useMonthEventBar.js
  front/src/mocks/api.js
  front/src/store/events.js
  front/src/store/selectors/calendars.js
  front/src/store/selectors/events.js
  front/src/utils/moment.js
Labels: ✨ feat, 👨‍💻 FE

#133 getAllEvent 수정
  back/routes/event.js
  back/routes/user.js
  back/utils/authJWT.js
  back/utils/jwt-util.js
  back/utils/refresh.js
Labels: ✨ feat, 👨‍💻 BE

#136 토큰 에러 수정
  back/utils/authJWT.js
  back/utils/refresh.js
Labels: 🐛 fix, 👨‍💻 BE

#138 토큰 오류 fix
  back/swagger/userAPI.yaml
  back/utils/authJWT.js
Labels: 🐛 fix, 👨‍💻 BE

#140 fix: AccessToken 갱신 실패인 경우, 스토어를 비운 후 강제 새로고침
  front/src/utils/token.js
Labels: ✨ feat, 👨‍💻 FE

#153 feat: 이벤트 생성 모달 구현 및 이벤트 목록 모달 수정 (#121, #151)
  front/public/img/google_meet_icon.png
  front/src/components/calendar/EventBar/style.module.css
  front/src/components/calendar/month/CalendarBody/Date/NewEvent/index.jsx
  front/src/components/calendar/month/CalendarBody/Date/style.module.css
  front/src/components/common/Modal/index.jsx
  front/src/components/common/Modal/style.module.css
  front/src/components/modal/CreateEventModal/index.jsx
  front/src/components/modal/CreateEventModal/style.module.css
  front/src/components/modal/EventDetailModal/index.jsx
  front/src/components/modal/EventDetailModal/style.module.css
  front/src/components/modal/layout/CreateModalLayout/index.jsx
  front/src/context/EventModalContext.js
  front/src/hooks/useEventModal.js
  front/src/hooks/useMonthEventBar.js
  front/src/pages/MonthCalendarPage/index.jsx
Labels: ✨ feat, 🎨 style, 👨‍💻 FE

#155 fix: PrivateEvent, calendar response 변경
  back/routes/calendar.js
  back/routes/privateEvent.js
Labels: 🐛 fix, 👨‍💻 BE

#156 fix: swagger 수정
  back/swagger.yaml
  back/swagger/calendarAPI.yaml
  back/swagger/privateEventAPI.yaml
Labels: 🐛 fix, 👨‍💻 BE

#158 style: 이벤트 목록 및 상세 정보 모달창 위치 조정
  front/src/components/calendar/month/CalendarBody/Date/EventList/index.jsx
  front/src/components/common/Modal/style.module.css
  front/src/components/modal/CreateEventModal/index.jsx
  front/src/components/modal/EventDetailModal/index.jsx
  front/src/components/modal/EventListModal/EventContainer/index.jsx
Labels: 🎨 style, 👨‍💻 FE
