Repository Project-calender/project-calendar, pull requests merged in 2022-06, with the labels that each got.

#20 chore: React + ESLint +Prettier 설정
  front/.eslintrc.js
Labels: ⚙ chore, 👨‍💻 FE

#23 calendar 컴포넌트
  front/src/App.js
  front/src/components/calendar/calendar.module.css
  front/src/components/calendar/index.jsx
  front/src/index.js
Labels: 👨‍💻 FE

#32 Feat/navbar UI
  front/package-lock.json
  front/package.json
  front/public/img/logo.png
  front/public/img/user_img.png
  front/src/App.js
  front/src/components/Navbar/index.jsx
  front/src/components/Navbar/style.module.css
  front/src/index.js
  front/src/pages/Main/index.jsx
  front/src/pages/Main/style.module.css
Labels: 👨‍💻 FE

#33 Feat/sidebar UI
  front/src/components/SideBar/AddEventButton/index.jsx
  front/src/components/SideBar/AddEventButton/style.module.css
  front/src/components/SideBar/CalendarList/CalendarInfo/index.jsx
  front/src/components/SideBar/CalendarList/CalendarInfo/style.module.css
  front/src/components/SideBar/CalendarList/index.jsx
  front/src/components/SideBar/CalendarList/style.module.css
  front/src/components/SideBar/MiniCalendar/CalendarHeader/index.jsx
  front/src/components/SideBar/MiniCalendar/CalendarHeader/style.module.css
  front/src/components/SideBar/MiniCalendar/Week/index.jsx
  front/src/components/SideBar/MiniCalendar/Week/style.module.css
  front/src/components/SideBar/MiniCalendar/WeekDaysHeader/index.jsx
  front/src/components/SideBar/MiniCalendar/index.jsx
  front/src/components/SideBar/MiniCalendar/style.module.css
  front/src/components/SideBar/MyCalendarList/index.jsx
  front/src/components/SideBar/SubscriptionCalendarList/index.jsx
  front/src/components/SideBar/SubscriptionCalendarList/style.module.css
  front/src/components/SideBar/UserSearch/index.jsx
  front/src/components/SideBar/UserSearch/style.module.css
  front/src/components/SideBar/index.jsx
  front/src/components/SideBar/style.module.css
  front/src/pages/Main/index.jsx
  front/src/pages/Main/style.module.css
  front/src/utils/moment.js
Labels: ✨ feat, 👨‍💻 FE

#34 style: SideBar 컴포넌트 스타일 지정 (#28)
  front/src/components/SideBar/AddEventButton/style.module.css
  front/src/components/SideBar/CalendarList/CalendarInfo/index.jsx
  front/src/components/SideBar/CalendarList/CalendarInfo/style.module.css
  front/src/components/SideBar/CalendarList/index.jsx
  front/src/components/SideBar/CalendarList/style.module.css
  front/src/components/SideBar/MiniCalendar/CalendarHeader/index.jsx
  front/src/components/SideBar/MiniCalendar/CalendarHeader/style.module.css
  front/src/components/SideBar/MiniCalendar/WeekDaysHeader/index.jsx
  front/src/components/SideBar/MiniCalendar/WeekDaysHeader/style.module.css
  front/src/components/SideBar/MiniCalendar/style.module.css
  front/src/components/SideBar/MyCalendarList/index.jsx
  front/src/components/SideBar/SubscriptionCalendarList/style.module.css
  front/src/components/SideBar/UserSearch/index.jsx
  front/src/components/SideBar/UserSearch/style.module.css
  front/src/components/SideBar/style.module.css
  front/src/components/common/Tooltip/index.jsx
  front/src/components/common/Tooltip/style.module.css
  front/src/pages/Main/style.module.css
Labels: 🎨 style, 👨‍💻 FE

#37 Side nav
  front/public/img/side_bar_icon1.png
  front/public/img/side_bar_icon2.png
  front/public/img/side_bar_icon4.png
  front/public/img/side_bar_icon5.png
  front/public/img/side_bar_icon6.png
  front/src/components/Navbar/LeftMenu/index.jsx
  front/src/components/Navbar/LeftMenu/style.module.css
  front/src/components/Navbar/RightMenu/index.jsx
  front/src/components/Navbar/RightMenu/style.module.css
  front/src/components/Navbar/index.jsx
  front/src/components/Navbar/style.module.css
  front/src/components/SideNav/index.jsx
  front/src/components/SideNav/style.module.css
  front/src/pages/Main/index.jsx
  front/src/pages/Main/style.module.css
Labels: 👨‍💻 FE
